dist: xenial

install:
 - sudo apt install -y qemu-system qemu-utils qemu qemu-user-static binfmt-support
 - wget https://downloads.raspberrypi.org/raspbian_lite_latest
 - unzip *.zip
 - rm *.zip

script:
 - ./setup2.sh
