dist: xenial

sudo: required

install:
 - sudo apt update
 - sudo apt install -y qemu
 - wget https://downloads.raspberrypi.org/raspbian_lite_latest
 - unzip *.zip
 - rm *.zip

script:
 - ./setup2.sh
